name: LagAssist
author: Stefatorus
version: 2.23.4
api-version: 1.13
description: LagAssist is an advanced anti-lag solution that allows server owners find and remove lag using multiple advanced and efficient methods.
main: cx.sfy.LagAssist.Main
softdepend: [Vault]
commands:
  lagassist:
    description: The main command of LagAssist, a Performance Analysis and Optimization Tool.
